name: CI - Train Rice Classification Model

on:
  push:
    branches: [main]
    paths:
      - "MLProject/**"
      - "split_dataset.py"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

jobs:
  train-model:
    name: Train Model with MLflow Project
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      # 3. Install semua dependensi
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kaggle mlflow==2.19.0 tensorflow==2.18.0 numpy pandas pillow scikit-learn

      # 4. Download Rice Image Dataset dari Kaggle (real dataset)
      - name: Download Dataset from Kaggle
        env:
          KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_TOKEN }}
        run: |
          mkdir -p MLProject/data_raw
          kaggle datasets download -d muratkokludataset/rice-image-dataset -p MLProject/data_raw --unzip
          echo "Dataset downloaded!"
          ls MLProject/data_raw/

      # 5. Split dataset jadi train/val/test (200 gambar/kelas)
      - name: Split Dataset
        run: |
          python split_dataset.py
          echo "Split selesai!"

      # 6. Jalankan MLflow Project (training dengan real data)
      - name: Run MLflow Project
        run: |
          mlflow run MLProject/ \
            -e main \
            --env-manager local \
            -P data_path=data_split \
            -P epochs=2

      # 7. Upload model artifact ke GitHub
      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rice-model-artifact
          path: rice_model_ci.keras
          retention-days: 30
