name: CI - Train Rice Classification Model

on:
  push:
    branches: [main]
    paths:
      - "MLProject/**"
      - "create_test_data.py"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

jobs:
  train-model:
    name: Train Model with MLflow Project
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      # 3. Install semua dependensi
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 tensorflow==2.18.0 numpy pandas pillow scikit-learn matplotlib

      # 4. Generate synthetic dataset untuk CI (pengganti dataset asli yang 75GB)
      - name: Generate Synthetic Test Dataset
        run: |
          python create_test_data.py

      # 5. Jalankan MLflow Project
      - name: Run MLflow Project
        run: |
          mlflow run MLProject/ \
            -e main \
            --env-manager local \
            -P data_path=MLProject/data_split \
            -P epochs=2

      # 6. Upload model artifact ke GitHub
      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rice-model-artifact
          path: rice_model_ci/
          retention-days: 30
